# Generated by Django 5.2.7 on 2025-10-27 02:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('state', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('zip_codes', models.JSONField(blank=True, default=list, help_text='List of ZIP codes for this town')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Towns',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TownChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_address', models.JSONField(help_text='Structured billing address for verification')),
                ('status', models.CharField(choices=[('pending', 'Pending Current Town Approval'), ('approved_current', 'Approved by Current Town'), ('approved_new', 'Approved by New Town'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by_current_town', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_outgoing_town_changes', to=settings.AUTH_USER_MODEL)),
                ('approved_by_new_town', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_incoming_town_changes', to=settings.AUTH_USER_MODEL)),
                ('current_town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_requests', to='towns.town')),
                ('requested_town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_requests', to='towns.town')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='town_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Town Change Requests',
                'ordering': ['-requested_at'],
            },
        ),
    ]
