# Generated by Django 5.2.7 on 2025-10-27 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='town',
            name='emergency_dispatch',
            field=models.CharField(blank=True, help_text='Emergency dispatch number', max_length=20),
        ),
        migrations.AddField(
            model_name='town',
            name='emergency_fire',
            field=models.CharField(default='911', help_text='Fire department emergency number', max_length=20),
        ),
        migrations.AddField(
            model_name='town',
            name='emergency_medical',
            field=models.CharField(default='911', help_text='Medical/EMS emergency number', max_length=20),
        ),
        migrations.AddField(
            model_name='town',
            name='emergency_non_urgent',
            field=models.CharField(blank=True, help_text='Non-urgent dispatch number', max_length=20),
        ),
        migrations.AddField(
            model_name='town',
            name='emergency_police',
            field=models.CharField(default='911', help_text='Police emergency number', max_length=20),
        ),
    ]
