# Generated by Django 5.2.7 on 2025-11-19 00:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0005_make_office_address_optional'),
        ('towns', '0002_town_emergency_dispatch_town_emergency_fire_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='town',
            name='approver',
            field=models.ForeignKey(blank=True, help_text='The government official designated to approve/reject citizens and business owners for this town', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_towns', to='government.governmentofficial'),
        ),
    ]
