# Generated by Django 5.2.7 on 2025-11-24 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('towns', '0003_add_town_approver'),
    ]

    operations = [
        migrations.AddField(
            model_name='town',
            name='emergency_animal_control',
            field=models.CharField(blank=True, help_text='Animal control emergency number', max_length=20),
        ),
        migrations.AddField(
            model_name='town',
            name='emergency_child_protective',
            field=models.CharField(blank=True, help_text='Child protective services number', max_length=20),
        ),
        migrations.AddField(
            model_name='town',
            name='emergency_mental_health',
            field=models.CharField(blank=True, help_text='Mental health crisis hotline', max_length=20),
        ),
        migrations.AddField(
            model_name='town',
            name='emergency_poison_control',
            field=models.CharField(blank=True, help_text='Poison control center number', max_length=20),
        ),
        migrations.AddField(
            model_name='town',
            name='emergency_public_works',
            field=models.CharField(blank=True, help_text='Public works emergency number', max_length=20),
        ),
        migrations.AddField(
            model_name='town',
            name='emergency_road_department',
            field=models.CharField(blank=True, help_text='Road/Highway department emergency', max_length=20),
        ),
        migrations.AddField(
            model_name='town',
            name='emergency_utilities',
            field=models.CharField(blank=True, help_text='Utilities emergency (gas, water, electric)', max_length=20),
        ),
    ]
