# Generated by Django 5.2.7 on 2025-12-09 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businessowner', '0004_eventregistration_servicebooking_businessnotification'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='businessnotification',
            new_name='businessown_busines_dea6fb_idx',
            old_name='businessown_business_created_idx',
        ),
        migrations.RenameIndex(
            model_name='businessnotification',
            new_name='businessown_is_read_1962be_idx',
            old_name='businessown_is_read_idx',
        ),
    ]
