# Generated by Django 5.2.7 on 2025-12-09 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businessowner', '0005_rename_businessown_business_created_idx_businessown_busines_dea6fb_idx_and_more'),
        ('government', '0009_billproposal_billcomment_billvote'),
        ('towns', '0004_town_emergency_animal_control_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='businesscomplaint',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='businesslicense',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='businesscomplaint',
            name='assigned_to',
            field=models.CharField(blank=True, help_text='Department or person assigned', max_length=200),
        ),
        migrations.AddField(
            model_name='businesscomplaint',
            name='estimated_resolution',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='businesscomplaint',
            name='location',
            field=models.CharField(blank=True, help_text='Location of the issue', max_length=200),
        ),
        migrations.AddField(
            model_name='businesscomplaint',
            name='town',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_complaints', to='towns.town'),
        ),
        migrations.AddField(
            model_name='businesslicense',
            name='attachments',
            field=models.JSONField(blank=True, default=list, help_text='List of attachment file paths/URLs'),
        ),
        migrations.AddField(
            model_name='businesslicense',
            name='fee',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Application or renewal fee', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='businesslicense',
            name='fee_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businesslicense',
            name='renewal_required',
            field=models.BooleanField(default=False, help_text='Whether this license requires periodic renewal'),
        ),
        migrations.AddField(
            model_name='businesslicense',
            name='review_comment',
            field=models.TextField(blank=True, help_text='Comments from government official during review'),
        ),
        migrations.AddField(
            model_name='businesslicense',
            name='review_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='businesslicense',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_licenses', to='government.governmentofficial'),
        ),
        migrations.AlterField(
            model_name='businesslicense',
            name='business_owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='businessowner.businessownerprofile'),
        ),
        migrations.AddIndex(
            model_name='businesslicense',
            index=models.Index(fields=['business_owner', 'status'], name='businessown_busines_c1fd0f_idx'),
        ),
        migrations.AddIndex(
            model_name='businesslicense',
            index=models.Index(fields=['status', '-created_at'], name='businessown_status_df72b5_idx'),
        ),
    ]
