# Generated by Django 5.2.7 on 2025-10-27 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizenprofile',
            name='billing_address',
            field=models.JSONField(blank=True, default=dict, help_text='Structured billing address'),
        ),
    ]
