# Generated by Django 5.2.7 on 2025-11-23 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0002_citizenprofile_billing_address'),
        ('towns', '0003_add_town_approver'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='citizencomplaint',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='citizencomplaint',
            name='assigned_to',
            field=models.CharField(blank=True, help_text='Department or person assigned', max_length=200),
        ),
        migrations.AddField(
            model_name='citizencomplaint',
            name='estimated_resolution',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='citizencomplaint',
            name='location',
            field=models.CharField(blank=True, help_text='Location of the issue', max_length=200),
        ),
        migrations.AddField(
            model_name='citizencomplaint',
            name='town',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='citizen_complaints', to='towns.town'),
        ),
    ]
