# Generated by Django 5.2.7 on 2025-11-23 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0004_complaintattachment'),
        ('government', '0008_announcementquestion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('is_notification', models.BooleanField(default=False, help_text='Whether this comment should notify the citizen')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='citizen.citizencomplaint')),
                ('official', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='government.governmentofficial')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
