# Generated by Django 5.2.7 on 2025-11-23 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0005_complaintcomment'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('complaint_update', 'Complaint Update'), ('announcement', 'Announcement'), ('general', 'General')], default='complaint_update', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='citizen.citizenprofile')),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='citizen.citizencomplaint')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['citizen', '-created_at'], name='citizen_cit_citizen_ce78fd_idx'), models.Index(fields=['is_read'], name='citizen_cit_is_read_c3e1a3_idx')],
            },
        ),
    ]
