# Generated by Django 5.2.7 on 2025-12-10 00:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofile_approved_at_userprofile_approved_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id_document', 'ID Document'), ('drivers_license', "Driver's License"), ('state_id', 'State ID'), ('passport', 'Passport'), ('government_id', 'Government ID'), ('business_document', 'Business Document'), ('other', 'Other')], default='id_document', max_length=50)),
                ('file', models.FileField(upload_to='user_documents/%Y/%m/%d/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(help_text='MIME type or file extension', max_length=50)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('description', models.TextField(blank=True, help_text='Optional description of the document')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
                'indexes': [models.Index(fields=['user', '-uploaded_at'], name='authenticat_user_id_19768c_idx'), models.Index(fields=['document_type'], name='authenticat_documen_528fb4_idx')],
            },
        ),
    ]
