# Generated by Django 5.2.7 on 2025-10-27 02:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0001_initial'),
        ('towns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentofficial',
            name='town',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='towns.town'),
        ),
    ]
