# Generated by Django 5.2.7 on 2025-11-18 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0003_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
