# Generated by Django 5.2.7 on 2025-11-19 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0004_alter_position_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='governmentofficial',
            name='office_address',
            field=models.TextField(blank=True),
        ),
    ]
