# Generated by Django 5.2.7 on 2025-11-19 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0005_make_office_address_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='governmentofficial',
            name='can_approve_users',
            field=models.BooleanField(default=False, help_text='If True, this government official can approve/reject citizens and business owners from their town'),
        ),
        migrations.AddField(
            model_name='governmentofficial',
            name='can_view_users',
            field=models.BooleanField(default=False, help_text='If True, this government official can view and manage citizen/business owner details'),
        ),
    ]
