# Generated by Django 5.2.7 on 2025-11-23 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0006_add_user_permissions'),
        ('towns', '0003_add_town_approver'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='announcement',
            name='description',
            field=models.TextField(blank=True, help_text='Short description for preview'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='List of tags'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='town',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='announcements', to='towns.town'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='type',
            field=models.CharField(choices=[('event', 'Event'), ('alert', 'Alert'), ('meeting', 'Meeting'), ('policy', 'Policy')], default='alert', max_length=20),
        ),
        migrations.AddField(
            model_name='announcement',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
