# Generated by Django 5.2.7 on 2025-11-23 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citizen', '0003_alter_citizencomplaint_options_and_more'),
        ('government', '0007_alter_announcement_options_announcement_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnnouncementQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('is_answered', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('announcement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='government.announcement')),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_questions', to='government.governmentofficial')),
                ('citizen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='citizen.citizenprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
