# Generated by Django 5.2.7 on 2025-12-09 22:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('government', '0008_announcementquestion'),
        ('towns', '0004_town_emergency_animal_control_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('summary', models.TextField(blank=True, help_text='Short summary for preview')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('implemented', 'Implemented'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('support_count', models.IntegerField(default=0)),
                ('oppose_count', models.IntegerField(default=0)),
                ('views', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('review_deadline', models.DateField(blank=True, null=True)),
                ('implementation_date', models.DateField(blank=True, null=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='List of tags')),
                ('attachments', models.JSONField(blank=True, default=list, help_text='List of attachment URLs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_bills', to='government.governmentofficial')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='government.department')),
                ('town', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bill_proposals', to='towns.town')),
            ],
            options={
                'verbose_name': 'Bill Proposal',
                'verbose_name_plural': 'Bill Proposals',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('likes', models.IntegerField(default=0)),
                ('is_edited', models.BooleanField(default=False)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_comments', to=settings.AUTH_USER_MODEL)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='government.billproposal')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BillVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_type', models.CharField(choices=[('support', 'Support'), ('oppose', 'Oppose')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='government.billproposal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_votes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('bill', 'user')},
            },
        ),
    ]
